### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by Bazsalanszky** [Bazsalanszky/p2p-chat#1]
Dolgok amiket meg kell csináljak:
- [x] ~~Map függvények átalakítása~~
   - [x] ~~Értékek lekérésének megváltoztatása~~
   - [x] ~~Bináris keresés~~
- [x] ~~Listening socket létrahozásának átrakása külön függvénybe~~ 
- [x] ~~ID létrehozás megváltoztatása~~
- [x] ~~RSA kulcs generálás kijavítása~~
- [x] ~~Konfigurációs fájl inicializálás~~
- [x] ~~Online/Offline státusz kiírása a chatablakban~~
- [x] ~~Specifikáció megírása~~
- [x] ~~Peer lista függvények átalakítása~~
- [x] ~~Több konfigurációs lehetőség~~
- [x] ~~Korábbi csevegések megjelenítése~~
- [x] ~~Dokumentáció megírása~~
- [ ] Jobb hibakezélés

**Comment by Bazsalanszky** [comment]
Az RSA titkosítást leveszem a listáról. Semmi szükség rá,csak bonyolítja a dolgot.
